apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-transactions-service
  labels:
    app: bank-transactions-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-transactions-service
  template:
    metadata:
      labels:
        app: bank-transactions-service
    spec: 
      containers:
      - name: bank-transactions-service
        image: smnikhilbharadwajsap/banktransactionsservice
        ports:
        - containerPort: 8080